### ISSUE TITLE
How to obtain depth information?

### ISSUE THREAD

**Issue by AgentEXPL** [hustvl/Symphonies#12]
Congratulations the acceptance of this great work. I have one question. The depth is generated by MobileStereoNet. Does it mean that the depth is predicted with two images from left and right camera? Then it may be unfair to compare with monoscene in  the task of "SSC from a single RGB image". Why not to use a depth predicted by a monocular depth estimation method？

**Comment by npurson** [comment]
Thanks for your interests in our work!

1. Indeed, we utilize stereo images for depth prediction, while employing features from monocular images for the rest scene modeling process. This setting is aligned with VoxFormer.
2. For a more fair comparison with MonoScene, you can refer to the results with monocular depth in Tab. 5.
3. The design choice to adopt stereo depth is to obtain a more accurate initial geometry, ensuring the consistency of 2D and 3D features for instance-centric aggregation.
