### ISSUE TITLE
数据集的设置

### ISSUE THREAD

**Issue by xinpuliu** [hustvl/Symphonies#13]
你好，我按照VoxFormer提供的https://github.com/NVlabs/VoxFormer/blob/main/docs/prepare_dataset.md整理好了数据，怎么和config里面的三个目录对应呢？
data_root: ？
label_root: ？
depth_root: ？
能否把您的数据文件夹结构截图一下呢，谢谢

**Comment by xinpuliu** [comment]
https://github.com/NVlabs/VoxFormer/blob/main/docs/prepare_dataset.md

**Comment by npurson** [comment]
以 https://github.com/NVlabs/VoxFormer/blob/main/docs/prepare_dataset.md#folder-structure 此处的文件夹结构为例，

data_root 应为 `kitti/`
label_root 应为 `kitti/dataset/labels`
depth_root 目录结构为

```
depth_root/
    └── sequences/
            ├── 00/
            │   ├── 000000.npy
            │   ├── 000005.npy
            |   .
            ├── 01/
            .
            └── 21/
```
