### ISSUE TITLE
Question about frustum loss

### ISSUE THREAD

**Issue by joonsu0109gh** [hustvl/Symphonies#16]
Hello, I have a question about your work.

I noticed that the config of symphonies(symphonies.yaml) includes a ‘frustum loss’ and that frustum loss is measured. However, the paper does not provide an explanation about frustum loss. Will the explanation be added to the accepted paper?

**Comment by npurson** [comment]
Uh-oh, I' think we will remove the frustum loss from the config, it doesn't influence the performance according to our experiments.
BTW, the frustum loss is introduced by MonoScene.
Thanks for your carefulness : )

**Comment by joonsu0109gh** [comment]
I got it. Thank you for the quick and kind answer!
