### ISSUE TITLE
The version of the pre-trained Mask DINO.

### ISSUE THREAD

**Issue by joonsu0109gh** [hustvl/Symphonies#17]
To my knowledge, Mask DINO does not provide panoptic segmentation on the KITTI dataset. Could you please specify which dataset your pre-trained Mask DINO model was trained on?

**Comment by npurson** [comment]
It is the official pre-trained weright on COCO dataset. You can find the reproduced preformance from the [README](https://github.com/hustvl/Symphonies/tree/main/maskdino).
