### ISSUE TITLE
KeyError: 'traitsui.toolkits'

### ISSUE THREAD

**Issue by Ha-coding-user** [hustvl/Symphonies#18]
When I visualize the result I meet this Error

> Traceback (most recent call last):
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 292, in __getitem__
>     return next(iter(self.select(name=name)))
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/hamyo/SSC/Symphonies/mmdetection/Symphonies/tools/visualize.py", line 9, in <module>
>     from mayavi import mlab
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/mayavi/mlab.py", line 16, in <module>
>     from mayavi.tools.camera import view, roll, yaw, pitch, move
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/mayavi/tools/camera.py", line 24, in <module>
>     from .engine_manager import get_engine
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/mayavi/tools/engine_manager.py", line 12, in <module>
>     from mayavi.preferences.api import preference_manager
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/mayavi/preferences/api.py", line 4, in <module>
>     from .preference_manager import preference_manager
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/mayavi/preferences/preference_manager.py", line 29, in <module>
>     from traitsui.api import View, Group, Item
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traitsui/api.py", line 256, in <module>
>     from .editors.api import ArrayEditor
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traitsui/editors/__init__.py", line 16, in <module>
>     from .api import ArrayEditor
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traitsui/editors/api.py", line 86, in <module>
>     from .code_editor import CodeEditor
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traitsui/editors/code_editor.py", line 21, in <module>
>     class CodeEditor(EditorFactory):
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traitsui/editors/code_editor.py", line 33, in CodeEditor
>     mark_color = Color(0xECE9D8)
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traits/trait_factory.py", line 40, in __call__
>     return self.maker_function(*args, **metadata)
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traitsui/toolkit_traits.py", line 43, in ColorTrait
>     return toolkit().color_trait(*args, **traits)
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/traitsui/toolkit.py", line 110, in toolkit
>     _toolkit = find_toolkit("traitsui.toolkits")
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/pyface/base_toolkit.py", line 285, in find_toolkit
>     plugin for plugin in importlib_metadata.entry_points()[entry_point]
>   File "/home/hamyo/anaconda3/envs/Symphonies/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 294, in __getitem__
>     raise KeyError(name)
> KeyError: 'traitsui.toolkits'

I check many method for solve above error
But I can't solve error

Please give me a solution

**Comment by npurson** [comment]
It appears to be an environmental issue with Mayavi. I also encountered some problems with Python 3.7, but I was able to resolve them by switching to Python 3.10.

**Comment by Ha-coding-user** [comment]
Thank you for your reply
Okay Now, I meet this error

> ImportError: Could not import backend for traitsui.  Make sure you
>         have a suitable UI toolkit like PyQt/PySide or wxPython
>         installed.

But I have installed pyqt5
I dont know why it is happened

**Comment by Ha-coding-user** [comment]
I meet this Error...
I dont know how to visualize results...

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted (core dumped)

Check and Reply Please...

**Comment by Ha-coding-user** [comment]
@npurson Okay I did some method
I think I need tell you about my config

I use Server(Ubuntu 18.04 LTS) and use Xming(for GUI) and PUTTY(for ssh protocol)
Is it something wrong?

If it has something wrong thing, please tell me how to train your model, and your computing spec

**Comment by npurson** [comment]
Unfortunately, I'm not familiar with this issue.

Several related discussions [[1](https://stackoverflow.com/questions/68036484/qt-qpa-plugin-could-not-load-the-qt-platform-plugin-xcb-in-even-though-it), [2](https://github.com/NVlabs/instant-ngp/discussions/300)] might offer some potential solutions.

I think it may be more helpful to search the solution or raise this issue directly within the [Mayavi](https://github.com/enthought/mayavi), as it seems to pertain specifically to the environment setup within their application.

**Comment by Ha-coding-user** [comment]
Okay I solve this Error And close it

**Comment by Li-ChangHao** [comment]
> Okay I solve this Error And close it

Hi, can you tell me how to solve it, I also encountered this error. Many thanks.
