### ISSUE TITLE
Adaptation of another dataset

### ISSUE THREAD

**Issue by SuNy4** [hustvl/Symphonies#20]
Hello, firstly thanks for new insights through your work. I have a question for adapting another dataset.

As far as I know, SSC voxel map of SemanticKITTI has a trail of moving object, providers called spatio-temporal tube.
I think this may affect metric scores or even performances of your work.
So I am trying to adapt Occ3D dataset to your work expecting better performances. (But It's not a stereo dataset)
Have you tried this dataset before or planned to adapt in future?

Again, thanks for your work! lots of things to learn from it.😊

**Comment by npurson** [comment]
Hi there, thanks for your interest in our work!

Regarding Occ3D, we're indeed working on it for our future work, but regrettably, we don't have any plans to adapt Symphonies to it at present.

BTW, I believe that multi-views on nuScenes can utilize even more geometrical cues than stereo does. Besides, there are also some more advanced metric depth estimation methods, such as Metric3D V2.

Please let us know if you have any other questions or progress!

**Comment by SuNy4** [comment]
Thanks for kind reply!

Your advice and opinion make me reconsider about geometrical enrichment.
I'll let you know if we had any progress!

Also I am looking forward your future work!
Thanks again!😊
