### ISSUE TITLE
How to organize the KITTI-360 dataset?

### ISSUE THREAD

**Issue by 3bobo** [hustvl/Symphonies#23]
Thanks for your great work! I want to train your model on the KITTI-360 dataset. I download the dataset following [this](https://github.com/ai4ce/SSCBench/tree/main/dataset/KITTI-360), and run the code `match_kitti_360_stereo.py`. However, it does not work. So I want to ask how to organize the KITTI-360 dataset and output their depth.

**Comment by npurson** [comment]
It appears that the SSCBench-KITTI-360 dataset has updated the stereo images in [recent commits](https://github.com/ai4ce/SSCBench/blame/993296e6957049c6ef5ded26ac6b9f0d794d986f/dataset/KITTI-360/README.md#L27). As a result, you can simply follow the same pre-processing steps of [stereo depth estimation for SemanticKITTI](https://github.com/NVlabs/VoxFormer/tree/main/preprocess#3-image-to-depth), with the exception of [adapting the disparity value](https://github.com/ai4ce/SSCBench/issues/8#issuecomment-1674607576).

Note that the `match_kitti_360_stereo.py` script is intended to find matched stereo pairs, which was previously necessary when these pairs were not provided.

**Comment by 3bobo** [comment]
Thank you for your reply! I'll take a try.
