### ISSUE TITLE
Question about performance between paper and github

### ISSUE THREAD

**Issue by joonsu0109gh** [hustvl/Symphonies#5]
There's a significant gap in performance, especially in mIoU, between GitHub and the paper. What could account for these differences?

**Comment by npurson** [comment]
We've identified and fixed several critical issues mostly related to coordinate calculation.

**Comment by joonsu0109gh** [comment]
Have the fixed issues been applied to this GitHub code?
I did not achieve the same scores as your pre-trained models during training.

Thank you for your answer :)

**Comment by npurson** [comment]
> Have the fixed issues been applied to this GitHub code? I did not achieve the same scores as your pre-trained models during training.
> 
> Thank you for your answer :)

Yes, the Github code and the released checkpoints are both up-to-date with the latest version.
What's your reproduced results? It's possible that slight fluctuations of ~0.3 mIoU may occur, but we have reproduced our highest reported results multiple times. If the difference is greater, could you please provide us with training logs or any additional information? As another option, you could try loading the released pre-trained checkpoints to see if they yield the same results.

Looking forward to your reply :)

**Comment by joonsu0109gh** [comment]
Confirmed that the performance is as good as on GitHub. Thank you!
